import { chromium } from "playwright";
import fs from "fs";
import path from "path";

const XML_PATH = "../assembler/output/program.xml";

(async () => {
  // Load XML generated by compiler
  const xmlText = fs.readFileSync(XML_PATH, "utf-8");

  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();

  // Open CodeAsthram
  await page.goto("https://hackpy.tarcin.in/");
  await page.waitForTimeout(6000); // Blockly load delay

  // Inject execution helper
  await page.addScriptTag({
    path: path.resolve("./execute_xml.js")
  });

  // Execute XML in browser
  const result = await page.evaluate(
    xml => window.executeXML(xml),
    xmlText
  );

  console.log("Execution result:", result);

  // Save outputs
  fs.mkdirSync("./output", { recursive: true });
  fs.writeFileSync("./output/result.xml", xmlText);
  fs.writeFileSync("./output/result.txt", result.python || "");

  await browser.close();
})();
